export default function WhyPrediction({ segment }) {
  if (!segment) return (
    <div className="bg-white rounded-2xl shadow-card border p-5 anim-in">
      <div className="eyebrow">Explain</div>
      <h3 className="section-title mb-2">Why this prediction?</h3>
      <div className="text-sm text-slate-400">No segment selected.</div>
    </div>
  );
  const bars = [
    ['Network load', segment.network_load],
    ['Tower distance', Math.min(100, (segment.tower_distance / 3) * 100)],
    ['Historical quality', segment.historical_quality],
    ['Movement density', segment.event_density * 100]
  ];
  return (
    <div className="bg-white rounded-2xl shadow-card border p-5 anim-in">
      <div className="eyebrow">Explain</div>
      <h3 className="section-title mb-3">Why this prediction?</h3>
      {bars.map(([k, v]) => (
        <div key={k} className="mb-2">
          <div className="flex justify-between text-xs">
            <span className="text-slate-500">{k}</span><span className="font-bold">{Math.round(v)}%</span>
          </div>
          <div className="h-2 bg-slate-100 rounded-full overflow-hidden" role="img" aria-label={`${k} ${Math.round(v)} percent`}>
            <div className="h-full rounded-full transition-all" style={{ width: `${v}%`, background: 'linear-gradient(90deg,#0a2540,#1d5cab)' }} />
          </div>
        </div>
      ))}
      <div className="text-2xl font-extrabold mt-1">
        {Math.round(segment.quality_score)} <span className="text-xs font-normal text-slate-400">/ 100</span>
      </div>
      <p className="text-xs text-slate-500 mt-1">
        Feature-based explanation (not generated by the ML model itself): high expected network load
        combined with weak tower availability and historically lower reliability in this segment.
      </p>
    </div>
  );
}
